// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQHbzhyHFgBE1kwc4ilZ7bhWDdu70hvqw',
    appId: '1:505133488815:web:896a290121b99204d8125a',
    messagingSenderId: '505133488815',
    projectId: 'kingo-project',
    authDomain: 'kingo-project.firebaseapp.com',
    storageBucket: 'kingo-project.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAyjeIPARABd0E7fw4-GAYG0eD-SqzBL84',
    appId: '1:983208648238:android:1f61777a5b8b150cc449bf',
    messagingSenderId: '983208648238',
    projectId: 'kingo-pro-new',
    storageBucket: 'kingo-pro-new.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQctiQsuSdG3lgR_dbSgMwLZBo27jniIw',
    appId: '1:983208648238:ios:2046e19a2b2be160c449bf',
    messagingSenderId: '983208648238',
    projectId: 'kingo-pro-new',
    storageBucket: 'kingo-pro-new.firebasestorage.app',
    iosBundleId: 'com.qeema.kingo.user',
  );
}
