// Mocks generated by Mockito 5.4.6 from annotations
// in heraj/test/features/bundle_order/bundle_order_use_cases_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:fpdart/fpdart.dart' as _i4;
import 'package:heraj/core/errors/failure.dart' as _i5;
import 'package:heraj/features/bundle_order/data/models/bundle_order_model.dart'
    as _i6;
import 'package:heraj/features/bundle_order/domain/entities/submit_bundle_params.dart'
    as _i8;
import 'package:heraj/features/bundle_order/domain/repo/bundle_order_repo.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [BundleOrderRepo].
///
/// See the documentation for Mockito's code generation for more information.
class MockBundleOrderRepo extends _i1.Mock implements _i2.BundleOrderRepo {
  MockBundleOrderRepo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<
      _i4.Either<_i5.Failure,
          List<_i6.BundleOrderModel>>> listMyBundleOrders() =>
      (super.noSuchMethod(
        Invocation.method(
          #listMyBundleOrders,
          [],
        ),
        returnValue: _i3
            .Future<_i4.Either<_i5.Failure, List<_i6.BundleOrderModel>>>.value(
            _i7.dummyValue<_i4.Either<_i5.Failure, List<_i6.BundleOrderModel>>>(
          this,
          Invocation.method(
            #listMyBundleOrders,
            [],
          ),
        )),
      ) as _i3.Future<_i4.Either<_i5.Failure, List<_i6.BundleOrderModel>>>);

  @override
  _i3.Future<_i4.Either<_i5.Failure, _i6.BundleOrderModel>>
      createBundleFromCart({String? notes}) => (super.noSuchMethod(
            Invocation.method(
              #createBundleFromCart,
              [],
              {#notes: notes},
            ),
            returnValue: _i3
                .Future<_i4.Either<_i5.Failure, _i6.BundleOrderModel>>.value(
                _i7.dummyValue<_i4.Either<_i5.Failure, _i6.BundleOrderModel>>(
              this,
              Invocation.method(
                #createBundleFromCart,
                [],
                {#notes: notes},
              ),
            )),
          ) as _i3.Future<_i4.Either<_i5.Failure, _i6.BundleOrderModel>>);

  @override
  _i3.Future<_i4.Either<_i5.Failure, _i6.BundleOrderModel>> showBundleByCode(
          String? code) =>
      (super.noSuchMethod(
        Invocation.method(
          #showBundleByCode,
          [code],
        ),
        returnValue:
            _i3.Future<_i4.Either<_i5.Failure, _i6.BundleOrderModel>>.value(
                _i7.dummyValue<_i4.Either<_i5.Failure, _i6.BundleOrderModel>>(
          this,
          Invocation.method(
            #showBundleByCode,
            [code],
          ),
        )),
      ) as _i3.Future<_i4.Either<_i5.Failure, _i6.BundleOrderModel>>);

  @override
  _i3.Future<_i4.Either<_i5.Failure, _i6.BundleOrderModel>> addMyCartToBundle(
          String? code) =>
      (super.noSuchMethod(
        Invocation.method(
          #addMyCartToBundle,
          [code],
        ),
        returnValue:
            _i3.Future<_i4.Either<_i5.Failure, _i6.BundleOrderModel>>.value(
                _i7.dummyValue<_i4.Either<_i5.Failure, _i6.BundleOrderModel>>(
          this,
          Invocation.method(
            #addMyCartToBundle,
            [code],
          ),
        )),
      ) as _i3.Future<_i4.Either<_i5.Failure, _i6.BundleOrderModel>>);

  @override
  _i3.Future<_i4.Either<_i5.Failure, bool>> removeMyBundleItem({
    required String? bundleCode,
    required int? bundleItemId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeMyBundleItem,
          [],
          {
            #bundleCode: bundleCode,
            #bundleItemId: bundleItemId,
          },
        ),
        returnValue: _i3.Future<_i4.Either<_i5.Failure, bool>>.value(
            _i7.dummyValue<_i4.Either<_i5.Failure, bool>>(
          this,
          Invocation.method(
            #removeMyBundleItem,
            [],
            {
              #bundleCode: bundleCode,
              #bundleItemId: bundleItemId,
            },
          ),
        )),
      ) as _i3.Future<_i4.Either<_i5.Failure, bool>>);

  @override
  _i3.Future<_i4.Either<_i5.Failure, bool>> cancelBundleOrder(String? code) =>
      (super.noSuchMethod(
        Invocation.method(
          #cancelBundleOrder,
          [code],
        ),
        returnValue: _i3.Future<_i4.Either<_i5.Failure, bool>>.value(
            _i7.dummyValue<_i4.Either<_i5.Failure, bool>>(
          this,
          Invocation.method(
            #cancelBundleOrder,
            [code],
          ),
        )),
      ) as _i3.Future<_i4.Either<_i5.Failure, bool>>);

  @override
  _i3.Future<_i4.Either<_i5.Failure, _i6.BundleOrderModel>> submitBundle(
          _i8.SubmitBundleParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #submitBundle,
          [params],
        ),
        returnValue:
            _i3.Future<_i4.Either<_i5.Failure, _i6.BundleOrderModel>>.value(
                _i7.dummyValue<_i4.Either<_i5.Failure, _i6.BundleOrderModel>>(
          this,
          Invocation.method(
            #submitBundle,
            [params],
          ),
        )),
      ) as _i3.Future<_i4.Either<_i5.Failure, _i6.BundleOrderModel>>);
}
